### ISSUE TITLE
Issues with index.html

### ISSUE THREAD

**Issue by AlexMakss** [QueM775/PHP_TV#1]
Issued #1 (minor)
1.1 if you make your window narrow enough the right DIV jump underneath left DIV. Not critical because TV is and always will be big.
1.2. if you click on the ["ADD text to the Right panel"] button, the text goes into wrong place. I guess it is just inappropriate target-DIV, later on it will be no data **just** in the id='idRightPanel' DIV, all html data will be in sub-DIV of the idRightPanel-DIV.
Issue #2 (major)
In my mind this index.html layout suppose to be the very !!basic!! (fundamental) layout of the PHP_TV project. Everything else suppose to be built ON TOP of this base. 
Question: if you are going to read PDF file, or select link to an external movie, why should you see "The Music Player here", "The Album image" and "The song title here" on your page?

**Comment by QueM775** [comment]
Hi Mike,

All good points but I do not see any issue. A Div can be displayed or not
display and the content of a Div can be dynamic not static. The player is
not displayed now when we
select movies or PDF  but it does display when we use audio books or music.
Just a we can hide section such as sub-folders if no content we can hide
other div's within a page
Perhaps we have a start page and the 2 sub pages is another option one for
audio and one for everything else. The key here and now is to take it easy
and think it out. All will
go a lot easier if we plan the layout correctly. I would as I mentioned be
changing the  items to flex so the layout I showed is just a draft a rough
draft. I will be working on things again today.
The thing to remember is these are not final until we say they are final.
We can change anything we want and now is the best time to do just that.

Cheers,
Erich

**Comment by AlexMakss** [comment]
OK ,  I will wait until you will say that this is "your final" version of the index.php layout. Then we will discuss "your final" layout and it will become "our final" layout.
It worries me a little bit when you are saying "have a start page and the 2 sub pages".
Please check how many pages do we have in the Smart_TV proj.? In my mind we have one and only one page. How many page's URL do we see in the address bar? Only one http://xxx.xxx.x.x/Smart_TV/default.asp?&with&some&parameters.
We have dozens of files in the project with (asp-functions, html-templates, js-codes, css-styles, images...) but non of these files are pages. I feel that we are not on the same page in term of terminology, but we have enough time to discuss everything before we start.

**Comment by QueM775** [comment]
Ok Mike, sounds good please have a look at the flex html file. I believe it covers our needs. It would be our template and we can hide and show what we want. I believe it is our final.

**Comment by AlexMakss** [comment]
Well, let's discuss the mechanism how will you hide (how to do it programmatically i.e. php/css/js/html) what you do not want to see on the page?
I can tell you how I can add **Something** to a page, if I need to see this **Something**.
Here it is:
```
<html>
<header>
</header>
<body>
<?php
IF (i-want-to-show-something == True){
   echo("<h1>Show-Something</h1>");
}
?>
</body>
</html>
```

**Comment by AlexMakss** [comment]
> I believe it covers our needs.

I covered functional coding in the Smart_TV project, in my estimation 80% of code was mine and 20% was yours. Design was 100% yours. In the PHP_TV project you should developed most of the functional code because you have to get familiar with PHP. I see my role as a helper. If you think that the current index.php file covers our needs we can start from here. You have clear understanding how the PHP_TV project should run at the end (very similar to what we have in Smart_TV). Now we have the starting point (index.php), it means we can start walking from start to end.
Due to learn PHP (I guess) you should ask me question like this: "I want to do **this**. How can I do it in PHP?" The term **this** should be very practical, technical, clear, basic and simple
How can I create a PHP function
How can I include PHP code from another PHP file (reusable code)
How can I read a text file
How can I connect to DB
as so on.
All logical and strategical solutions we can borrow from Smart_TV project.
This is my vision.
Agreed?

**Comment by QueM775** [comment]
I agree, I think I need to hammer this out and if I hit a wall I should have you to ask. I think we can discuss it on our call in more detail.

**Comment by AlexMakss** [comment]
\* * * to hammer * * * if I hit a wall * * * I will use you as a hammer :-)

**Comment by QueM775** [comment]
OK it sounds like we are on the same page. Going forward we can close this issue.
